#=
This program download all the Laplacians generated by 
running IPM on some Chimera graphs and Spielman graphs.
These matrices are hosted on suitesparse.
=#


include("../julia-files/downloadSS.jl")

println("---------------")
println("Downloading chimeras")
println("---------------")

n = Int64(1e5)
epsInterval = [1 / 10^j for j in 1:6]

for i in 1:5
    println("---------------")
    println("n = $(n), i = $(i) started")
    println("---------------")
    L = spzeros(n, n)
    for curTargetEps in epsInterval
        println("---------------")
        println("Current target eps $(curTargetEps)")
        println("---------------")
        for cnt in 1:6
            M = nothing
            try
                M = downloadSS("uc.i$(i).eps$(curTargetEps).$(cnt)"; remove=false)
            catch
                println("For target eps $(curTargetEps), there is only $(cnt - 1) instances")
                break
            end
            if isnothing(M) || M == -1
                println("Target eps $(curTargetEps), Laplacian $(cnt) failed to download.")
            end
        end
    end

    println("---------------")
    println("n = $(n), i = $(i) end")
    println("---------------")
end

println("---------------")
println("Finished downloading chimeras")
println("---------------")

println("---------------")
println("Downloading spielman graphs")
println("---------------")

for k in 100:100:600
    #@load "../matrix-files/badFlowIPMLap$(i).jld2"
    #lap1 = copy(lap)
    println("---------------")
    println("k = $(k) started")
    println("---------------")


    for i in 1:11
        println("---------------")
        println("i = $(i) started")
        println("---------------")
        M = nothing
        try
            M = downloadSS("sk$(k)i$(i)"; remove=false)
        catch
            println("For k = $(k), ipm in r-space with low eps only stored $(i-1) instances.")
            break
        end
        if isnothing(M) || M == -1
            println("For k = $(k), Laplacian $(i) failed to download")
        end
    end
    println("---------------")
    println("k = $(k) finished")
    println("---------------")
end

println("---------------")
println("Finished downloading spielman graphs")
println("---------------")